# -*- coding: utf-8 -*-
"""SREpHR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tMgvLPFnasOS4nBQ6F7jrpqoz_9zyOSg
"""

!pip install facenet-pytorch minisom

import torch
import torch.nn as nn
from torch.utils.data import DataLoader, Subset, random_split
from torchvision import datasets, transforms
from torchvision.models import resnet50, ResNet50_Weights
from google.colab import drive
import random
import math
import matplotlib.pyplot as plt
import numpy as np
from collections import Counter
from facenet_pytorch import InceptionResnetV1
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from minisom import MiniSom

from google.colab import drive

drive.mount('/content/drive')
!unzip -q "/content/drive/MyDrive/datasets.zip" -d "/content/datasets"
!cp "/content/drive/MyDrive/final_resnet50_amp_7.pth" "/content/final_resnet50_amp_7.pth"
# Remove Contempt
!mkdir '/content/separated_dataset'
!mkdir '/content/separated_test_dataset'
!mv '/content/datasets/separated_dataset/7' '/content/separated_dataset/7'
!mv '/content/datasets/separated_test_dataset/7' '/content/separated_test_dataset/7'

seed = 42
random.seed(seed)
np.random.seed(seed)
torch.manual_seed(seed)
torch.cuda.manual_seed_all(seed)
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

data_dir = '/content/datasets/separated_dataset'
test_data_dir = '/content/datasets/separated_test_dataset'

# transform and class weights
mean = [0.485, 0.456, 0.406]
std = [0.229, 0.224, 0.225]

data_transforms = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=mean,
                         std=std)
])

full_dataset = datasets.ImageFolder(root=data_dir, transform=data_transforms)
targets = full_dataset.targets

print("Classes:", full_dataset.classes)
num_classes = len(full_dataset.classes)

train_indices, val_indices = train_test_split(
    np.arange(len(targets)),
    test_size=0.05,
    random_state=seed,
    stratify=targets
)

train_dataset = Subset(full_dataset, train_indices)
val_dataset = Subset(full_dataset, val_indices)

print(f"Train size: {len(train_dataset)}, Val size: {len(val_dataset)}")

test_dataset = datasets.ImageFolder(root=test_data_dir, transform=data_transforms)
print(f"Test size: {len(test_dataset)}")

targets = [label for _, label in full_dataset.samples]
class_counts = Counter(targets)
total_samples = len(targets)

weights = []
for i in range(num_classes):
    class_count = class_counts[i]
    weight = total_samples / (num_classes * class_count)
    weights.append(weight)

weights = torch.tensor(weights, dtype=torch.float32)

device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")


num_emotions = num_classes

backbone = InceptionResnetV1(pretrained='vggface2', classify=False)
backbone.classify = False

class InceptionResnetV1EmotionClassification(nn.Module):
    def __init__(self, backbone, num_classes):
        super().__init__()
        self.backbone = backbone

        self.classifier = nn.Sequential(
            nn.Linear(512, 256),
            nn.ReLU(inplace=True),
            nn.Dropout(0.5),
            nn.Linear(256, num_classes)
        )

    def forward(self, x):
        emb = self.backbone(x)
        logits = self.classifier(emb)
        return logits

model = InceptionResnetV1EmotionClassification(backbone, num_emotions).to(device)
weights = weights.to(device)

#weights_model = ResNet50_Weights.DEFAULT
#model = resnet50(weights=weights_model)
#model.fc = nn.Sequential(
#    nn.Linear(model.fc.in_features, 256),
#    nn.ReLU(),
#    nn.Dropout(0.5),
#    nn.Linear(256, num_classes)
#)
#model.to(device)

def compute_per_class_acc(model, dataloader, device, num_classes):
    model.eval()
    correct = torch.zeros(num_classes)
    total   = torch.zeros(num_classes)

    with torch.no_grad():
        for images, labels in dataloader:
            images = images.to(device)
            labels = labels.to(device)

            logits = model(images)
            preds = torch.argmax(logits, dim=1)

            for l, p in zip(labels, preds):
                total[l] += 1
                if l == p:
                    correct[l] += 1

    per_class_acc = correct / total.clamp(min=1)
    return per_class_acc.cpu()

criterion = nn.CrossEntropyLoss(weight=weights)

optimizer = torch.optim.Adam(model.parameters(), lr=0.0001) #0,00005
scaler = torch.cuda.amp.GradScaler()

batch_size = 64
num_workers = 2

val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False, num_workers=num_workers, pin_memory=torch.cuda.is_available())
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False, num_workers=num_workers, pin_memory=torch.cuda.is_available())

train_losses = []
train_accuracies = []
val_losses = []
val_accuracies = []
num_epochs = 40 #20
subset_fraction = 0.1

best_macro_avg = 0.0
best_model_path = "best_macro_model.pth"

for epoch in range(num_epochs):
    subset_size = max(1, int(len(train_dataset) * subset_fraction))
    indices = random.sample(range(len(train_dataset)), subset_size)
    subset_epoch_dataset = Subset(train_dataset, indices)
    subset_loader = DataLoader(subset_epoch_dataset, batch_size=batch_size, shuffle=True, num_workers=num_workers, pin_memory=torch.cuda.is_available())

    # train
    model.train()
    running_loss = 0.0
    correct = 0
    total = 0

    for inputs, labels in subset_loader:
        inputs, labels = inputs.to(device), labels.to(device)

        optimizer.zero_grad()
        with torch.cuda.amp.autocast():
            outputs = model(inputs)
            loss = criterion(outputs, labels)

        scaler.scale(loss).backward()
        scaler.step(optimizer)
        scaler.update()

        running_loss += loss.item() * inputs.size(0)
        _, preds = torch.max(outputs, 1)
        correct += (preds == labels).sum().item()
        total += labels.size(0)

    epoch_loss = running_loss / total
    epoch_acc = correct / total
    train_losses.append(epoch_loss)
    train_accuracies.append(epoch_acc)

    print(f"Epoch {epoch+1}/{num_epochs} - Train Loss: {epoch_loss:.4f} - Train Acc: {epoch_acc:.4f}")

    # val
    model.eval()
    val_loss = 0.0
    val_correct = 0
    val_total = 0
    with torch.no_grad():
        for inputs, labels in val_loader:
            inputs, labels = inputs.to(device), labels.to(device)
            outputs = model(inputs)
            loss = criterion(outputs, labels)

            val_loss += loss.item() * inputs.size(0)
            _, preds = torch.max(outputs, 1)
            val_correct += (preds == labels).sum().item()
            val_total += labels.size(0)

    val_epoch_loss = val_loss / val_total
    val_epoch_acc = val_correct / val_total
    val_losses.append(val_epoch_loss)
    val_accuracies.append(val_epoch_acc)
    print(f"Epoch {epoch+1}/{num_epochs} - Val Loss: {val_epoch_loss:.4f} - Val Acc: {val_epoch_acc:.4f}\n")

    # after each epoch on val_loader
    all_preds, all_labels = [], []
    with torch.no_grad():
        for x, y in val_loader:
            x = x.to(device)
            y = y.to(device)
            logits = model(x)
            preds = torch.argmax(logits, dim=1)
            all_preds.extend(preds.cpu().numpy())
            all_labels.extend(y.cpu().numpy())

    report = classification_report(
        all_labels, all_preds,
        target_names=full_dataset.classes,
        output_dict=True
    )

    print(report)

    macro_f1 = report['macro avg']['f1-score']

    if macro_f1 > best_macro_avg:
        best_macro_avg = macro_f1
        torch.save(model.state_dict(), best_model_path)
        print(f"Best model saved at epoch {epoch+1}, macro_avg Acc: {best_macro_avg:.4f}")

model_save_path = "inceptionResnet50_stratified_40.pth"
torch.save(model.state_dict(), model_save_path)
print(f"Final model saved to {model_save_path}")

model.load_state_dict(torch.load(model_save_path)) #best_model_path
model.to(device)
model.eval()

all_preds = []
all_labels = []

test_loss = 0.0
test_correct = 0
test_total = 0
with torch.no_grad():
    for inputs, labels in test_loader:
        inputs, labels = inputs.to(device), labels.to(device)
        outputs = model(inputs)
        loss = criterion(outputs, labels)

        test_loss += loss.item() * inputs.size(0)
        _, preds = torch.max(outputs, 1)
        test_correct += (preds == labels).sum().item()
        test_total += labels.size(0)

        all_preds.append(preds.cpu())
        all_labels.append(labels.cpu())

all_preds = torch.cat(all_preds).numpy()
all_labels = torch.cat(all_labels).numpy()

print(f"Test Loss: {test_loss/test_total:.4f} - Test Acc: {test_correct/test_total:.4f}")

print(classification_report(
        all_labels, all_preds,
        target_names=full_dataset.classes,
        output_dict=True
    ))

epochs_range = range(1, num_epochs + 1)
plt.figure(figsize=(12, 5))

plt.subplot(1, 2, 1)
plt.plot(epochs_range, train_losses, label='Train Loss')
plt.plot(epochs_range, val_losses, label='Val Loss')
plt.xlabel("Epochs")
plt.ylabel("Loss")
plt.title("Loss")
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(epochs_range, train_accuracies, label='Train Acc')
plt.plot(epochs_range, val_accuracies, label='Val Acc')
plt.xlabel("Epochs")
plt.ylabel("Accuracy")
plt.title("Accuracy")
plt.legend()

plt.tight_layout()
plt.show()

print(classification_report(all_labels, all_preds, digits=2))
cm = confusion_matrix(all_labels, all_preds)
print("Confusion matrix:\n", cm)

model_load_path = "final_resnet50_amp_7.pth"
model.load_state_dict(torch.load(model_load_path, map_location=torch.device('cpu')))
model.to(device)

model.eval()

class FeatureExtractor(torch.nn.Module):
    def __init__(self, backbone):
        super().__init__()
        self.features = torch.nn.Sequential(*list(backbone.children())[:-1])

    def forward(self, x):
        x = self.features(x)
        x = torch.flatten(x, 1)
        return x

feature_extractor = FeatureExtractor(model).to(device)

all_feats = []
all_labels = []

with torch.no_grad():
    for inputs, labels in test_loader:
        inputs = inputs.to(device)
        feats = feature_extractor(inputs)
        all_feats.append(feats.cpu().numpy())
        all_labels.append(labels.numpy())

X = np.concatenate(all_feats, axis=0)
y = np.concatenate(all_labels, axis=0)
feature_dim = X.shape[1]

print("Feature matrix shape:", X.shape)
print("Labels shape:", y.shape)

som_rows, som_cols = 8, 8
som = MiniSom(
    x=som_rows,
    y=som_cols,
    input_len=feature_dim,
    sigma=1.0,
    learning_rate=0.5,
    neighborhood_function='gaussian',
    random_seed=42
)

som.random_weights_init(X)
print("Training SOM...")
som.train_random(X, num_iteration=5000)
print("SOM training done.")

num_classes = len(full_dataset.classes)
bmu_class_counts = np.zeros((som_rows, som_cols, num_classes), dtype=int)

for feat, label in zip(X, y):
    i, j = som.winner(feat)
    bmu_class_counts[i, j, label] += 1

colors = plt.cm.tab10(np.linspace(0, 1, num_classes))

max_total = bmu_class_counts.sum(axis=2).max()
class_names = full_dataset.classes

plt.figure(figsize=(6, 6))

for i in range(som_rows):
    for j in range(som_cols):
        class_counts = bmu_class_counts[i, j]
        total = class_counts.sum()
        if total == 0:
            continue

        majority_class = np.argmax(class_counts)
        majority_count = class_counts[majority_class]

        size = 50 + 250 * (total / max_total)

        plt.scatter(
            j,
            som_rows - 1 - i,
            s=size,
            c=[colors[majority_class]],
            alpha=0.8
        )

plt.xticks(range(som_cols))
plt.yticks(range(som_rows))
plt.grid(True, linestyle=":", linewidth=0.5)
plt.xlabel("Neuron column")
plt.ylabel("Neuron row")
plt.title("Emotion class distribution on SOM")

handles = [
    plt.Line2D([0], [0], marker='o', linestyle='',
               color=colors[k], label=class_names[k])
    for k in range(num_classes)
]
plt.legend(handles=handles, bbox_to_anchor=(1.05, 1), loc='upper left', title="Classes")

plt.tight_layout()
plt.show()